### ISSUE TITLE
Installation instructions cleanup

### ISSUE THREAD

**Issue by brynpickering** [LBNL-ETA/MSWH#10]
The README installation instructions are a bit confusing and occasionally miss some steps:

1. It's a bit difficult to read the conda/virtualenv instructions since you switch between them on different lines. Would a code block on installation with conda and another with virtualenv be possible? You can always put comments in those code blocks to describe what's going on.

2. You also need to add `pip` as a conda dependency. I expected it to be installed when installing python, but that seems to have changed.

3. A nice cross-platform method to install `git-lfs` is via conda forge, so you may find it easier to give instructions purely with conda:
```
conda create -n mswh -c conda-forge python=3.6 pip git-lfs
conda activate mswh
git lfs install
git clone ...
pip install -e .
```

4. `git lfs clone` is [deprecated](https://github.com/git-lfs/git-lfs/pull/2526) and they now recommend using `git clone`.

5. I generally recommend pointing people to [miniconda](https://docs.conda.io/en/latest/miniconda.html) rather than the full Anaconda distribution, since it has a much lower disk usage. 

Note: this issue comes to you as part of my wider [JOSS review](https://github.com/openjournals/joss-reviews/issues/2695)

**Comment by milicag** [comment]
- [x] pip installation instruction
- [x] `git-lfs` update
- [x] improve `virtualenv` instruction formatting
- [x] recommend miniconda

**Comment by brynpickering** [comment]
Thanks for making the changes @milicag. The instructions seem to have lengthened as a result, whereas I would say that minimising the length of installation instructions is key to being approachable to non-technical users.
If you have a non-technical user, they don't care about exactly what's happening (cloning, virtual environments, dependencies, pip -e flag, etc.), but most likely just want to get the web interface up and running on their machine. 
If they are a technical user, then they will know how to install a pip package locally and will have a personal preference for conda/virtaulenv - i.e. there's no need to instruct them on the process.
Based on that, I would have a single code block in your README, and the more detailed instructions in the documentation. This would ensure you're not duplicating installation instructions (as noted in #15), whilst not polluting the README with excessive detail. All that requires then is to choose your preference of conda/virtualenv and have a single code block for it. For conda, it would be:

```
 conda create -n mswh -c conda-forge -c plotly python=3.8 pip git-lfs jupyter plotly-orca
 conda activate mswh
 git lfs install
 git clone https://github.com/LBNL-ETA/MSWH.git
 pip install -e .
```

Note that this installs the necessary elements to run a jupyter notebook (I include the whole jupyter package, since non-technical users will have no way to use `ipykernel` by itself) and to save plots with `orca`. Does it include redundant dependencies if someone doesn't use the notebook or plotting functionality in the end? Yes, but then the time to run and resulting memory footprint is low enough not to matter. The upside is that non-technical users will have everything without needing to deal with error messages and understanding how to install packages within their environment after the fact. Technical users will install via pip in whatever way they like, and then they won't get those redundant packages unless they want them at a later date (or can choose the more lightweight `ipykernel` for accessing MSWH from their jupyter notebook/lab session).

If a non-technical user loves it and wants to dig deeper, then your documentation will be their source, and right there will be your extended instructions along with explanation as to what's going on.

**Comment by milicag** [comment]
I like that idea. @nmstreethran, do you find this to be a suitable solution? It satisfies my need to not repeat myself and it is going to make the instructions short and easy! All the good things.

**Comment by nmstreethran** [comment]
@milicag, yes, this solution is perfect!

EDIT: I think you'll need to install `notebook` (to install Jupyter Notebook) or `jupyterlab`, not `jupyter`.

**Comment by milicag** [comment]
To self: For good info on git-lfs provide: https://github.com/git-lfs/git-lfs/wiki/Installation link.

**Comment by milicag** [comment]
This is just to remind the reviewers that I'm not dropping the ball on this, just waiting for the weekend to get some time on it.

**Comment by milicag** [comment]
@nmstreethran : I think @brynpickering suggests `jupyter` here:

```
conda create -n mswh -c conda-forge -c plotly python=3.8 pip git-lfs jupyter plotly-orca
```

I personally usually install `jupyter lab` these days. If we keep arguing about this level of detail we will not get a chance to show the actual benefit of having these simulation models in Python. If you both agree that this is something that is interesting for JOSS please make it possible for me to help that effort out, tidy up the essentials and ensure needed functionality. Otherwise it might become uninteresting for me if we keep re-arranging the installation instructions.

**Comment by nmstreethran** [comment]
@milicag Alright, I'll leave the installation instructions as it is.

**Comment by brynpickering** [comment]
Yeah, let's go with jupyterlab, since it's also my preference for personal use (and a newbie might as well start with the more feature-complete version of Jupyter), so:

```
conda create -n mswh -c conda-forge -c plotly python=3.8 pip git-lfs jupyterlab plotly-orca
```
And then just link to the [JupyterLab documentation](https://jupyterlab.readthedocs.io/en/latest/) for people to get up and running with that.
