### ISSUE TITLE
JOSS Review: Installation instructions and Django application name

### ISSUE THREAD

**Issue by nmstreethran** [LBNL-ETA/MSWH#13]
Hi @milicag, I am [reviewing your JOSS submission](https://github.com/openjournals/joss-reviews/issues/2695) and have some initial comments regarding the installation instructions in the README file, and the Django web application. I will open a new issue once I have fully explored the code and functionality. I will also address the software paper and documentation in separate issues. Let me know if you have any questions. Thanks.

### Creating a virtual environment

The link to the guide on virtual environments should be updated to <https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/>.

Creating a new virtual environment on Linux should be done using the `venv` package (i.e., same as macOS; `virtualenv` is recommended for Python 2). From the link above:

> If you are using Python 3.3 or newer, the venv module is the preferred way to create and manage virtual environments. venv is included in the Python standard library and requires no additional installation.

I think the command for creating a virtual environment on Linux with a specific Python version could be removed, as it only works with `virtualenv`.

### `ipykernel`

`ipykernel` must be installed in the environment using `pip` or `conda` prior to running the command outlined in this step. From the [docs](https://ipython.readthedocs.io/en/stable/install/kernel_install.html):

> The Jupyter Notebook and other frontends automatically ensure that the IPython kernel is available. However, if you want to use a kernel with a different version of Python, or in a virtualenv or conda environment, you’ll need to install that manually.

Alternatively, `ipykernel` can be added to the dependencies list and installed after creating and activating the virtual environment to prevent this issue.

Users without admin privileges must include the `--user` flag when registering the kernel:

```sh
python -m ipykernel install --user --name mswh
```

### Other suggestions

- (line 8; paragraph 3) tankeless -> tankless
- (line 8; paragraph 4) link to the database has a typo; should be `mswh/comm/mswh_system_input.db`
- (line 11) latex -> LaTeX
- (line 11) html -> HTML
- (line 27) repo -> repository
- (lines 42, 46) MacOS / Mac -> macOS
- (line 66) jupyter -> Jupyter
- (lines 66, 86) python -> Python
- (line 88, sentence 3) can created -> can **be** created

## Django Web Framework Deployment

The web application is named 'Solar Water Heating' instead of 'Multiscale Solar Water Heating'. Is this intended?

**Comment by milicag** [comment]
Thanks @nmstreethran! @brynpickering also asked for changes in the readme, so I intend to blend your suggestions in. I do like to insist on a specific python version, so I maybe I might need to keep the `virtualenv`? It is what I still use with python3.8, that is my main development python version at the moment. It is one thing what one finds online and the other what one finds useful as a practitioner. I can mention it as an alternative for folks who care less about the python version.

Doesn't `ipykernel` get installed with jupyter notebook or jupyter lab? If not, I can add it separately.

To do:

- [x] address other suggestions
- [x] django package name - update to MSWH
- [x] add Jupyter installation info

**Comment by milicag** [comment]
@nmstreethran Please see my intended approach above and let me know if you have any objections. This applies to issues #15 and #14 as I have left similarly structured comments in those issues too. After I hear from you on all 3 issues I will start addressing them.

**Comment by milicag** [comment]
@hannesb0 May I leave it up to you to update the django application name? I don't know where I would need to change that. From my perspective it can also stay as is. <- never mind, I just did a string replace in the `web` folder.

**Comment by milicag** [comment]
This is now all addressed in PR #12.

**Comment by nmstreethran** [comment]
@milicag, thanks for addressing the issues! The changes look fine to me, apart from a couple of things:

- The instructions for using `conda` could be moved to the top. Otherwise, `conda` users will go through two separate instructions for installing Git LFS.
- Since you're keeping `virtualenv`, wouldn't it be better to change the link to the virtual environment guide in README.md to `virtualenv`'s docs? The current link could confuse users as it says `venv` is preferred for newer Python versions.

> Doesn't `ipykernel` get installed with jupyter notebook or jupyter lab? If not, I can add it separately.

Yes, `ipykernel` is a dependency of `notebook`, which is a dependency of `jupyterlab`. As long as one of these packages is installed in the virtual environment prior to registering the kernel, the installation should proceed. The users following the `conda` instructions must install `notebook` or `jupyterlab` separately as well, as neither are included in the requirements in `setup.py`.

EDIT: I also suggest changing 'repo' to 'repository'.
