### ISSUE TITLE
JOSS Review: Documentation

### ISSUE THREAD

**Issue by nmstreethran** [LBNL-ETA/MSWH#15]
[JOSS review](https://github.com/openjournals/joss-reviews/issues/2695): comments on the documentation

## A statement of need

A statement of need is required in the documentation -- same as the software paper.

## Installation instructions

The set-up and installation instructions should be in the documentation too, rather than directing users to view the README file on the GitHub repository.

## Functionality documentation

`scripts/Project Level MSWH System Tool.ipynb` and `scripts/Project Level SWH System Tool.ipynb` have been mentioned in `mswh/system/components.py` and `mswh/system/models.py`, but these files do not exist.

## Automated tests

Steps to run the functional and unit tests should be included here.

## Community guidelines

There should be a section with guidelines on how to contribute to the code, report issues, and seek support. It should mention that development takes place on GitHub. The README file says to check the documentation for guidance but I cannot seem to find any.

## Other suggestions

`docs/source/models.rst`

- (line 29) tankeless -> tankless
- (line 29) basecase -> base case
- (line 42) CSI -> California Solar Initiative

`mswh/comm/create_or_update_db.py`

- (line 140) monochrystalline -> monocrystalline
- (line 141) polychrystalline -> polycrystalline

`mswh/comm/label_map.py`

- (line 21) Occupancy

`mswh/comm/sql.py`

- (line 44) tables
- (line 160) execute

`mswh/system/components.py`

- (line 27) timeseries
- (line 929) aperture (?)
- (line 1248) medium
- (line 1497) temperature
- (line 1754) predefined temperature
- (line 2263) square
- (line 2964) Initial
- (line 2974) parallel
- (line 2975) circulation

`mswh/tools/plots.py`

- (line 286) length

`mswh/tools/unit_converters.py`

- (lines 47, 66) milion -> million
- (lines 56, 75) mili -> milli
- (lines 58, 77) mikro -> micro

**Comment by milicag** [comment]
@nmstreethran This is very helpful! Please see my comments below. The boxes represent what I intend to address, as in my responses in the rest of the issues you've created.

Where in the JOSS documentation do you require the code package to have documentation and describe the required form of that documentation? In my understanding JOSS only requires the paper to satisfy the JOSS paper requirements, which seems extremely logical.

I like to not repeat myself, so the installation will stay in the readme as it is fully accessible to those that read the sphinx docs, that are not really required by JOSS in the first place.

- [x] update notebook names to latest version in t `models.py` and `components.py`

The readme provides an info on [how to run tests under contributing](https://github.com/LBNL-ETA/MSWH#contributing). Would you like to have a subtitle that says `Automated tests` in addition to that? I could do that.

- [x] address `Other suggestions`. Thanks for doing this!

**Comment by milicag** [comment]
I addressed the issue in PR #12.

**Comment by milicag** [comment]
Thanks for finding all the glitches and I hope #12 addresses them well.

**Comment by nmstreethran** [comment]
Thanks @milicag. I am following the JOSS review checklist; each heading in this issue refers to a checklist item. You can see the checklist in https://github.com/openjournals/joss-reviews/issues/2695.

The software documentation is indeed part of your JOSS submission. From the [Review criteria](https://joss.readthedocs.io/en/latest/review_criteria.html):

> There should be sufficient documentation for you, the reviewer to understand the core functionality of the software under review. A high-level overview of this documentation should be included in a `README` file (or equivalent).

So, the documentation should include the items I've mentioned, and the README file should contain an overview.

The other changes look good to me, apart from a couple of things:

- `docs/source/models.rst` (line 29) basecase -- it's written as 'base case' in README.md, and 'basecase' here
- `mswh/system/components.py` (line 1248) medium

**Comment by milicag** [comment]
Revised README and split the installation instruction into two sections - simple and advanced.
