### ISSUE TITLE
(git)ignore test results

### ISSUE THREAD

**Issue by brynpickering** [LBNL-ETA/MSWH#19]
The output PNGs of tests should be in the gitignore, so they don't pollute the repository. Easiest is probably to ignore all PNGs, but you might want to point it only on test directories, if you envision having images elsewhere in the repository.

Note: this issue comes to you as part of my wider [JOSS review](https://github.com/openjournals/joss-reviews/issues/2695)

**Comment by milicag** [comment]
I commit the images to the repository, so I do need to track them with git. They are in the correct place on the repo.

**Comment by brynpickering** [comment]
Is there any reason to track them? As in, do you use them for things other than to verify tests?

**Comment by milicag** [comment]
Yes, they get visually inspected each time I run the tests for any issues, so I commit them from time to time. If I ignore them then I won't be able to commit them when I'd like to. The motivation is that I do want that visual information on the repo, tests are for developers and developers should know how to deal with those and ignore when needed and push up should there be changes to the test. Non-technical user will not run tests, rather will look at primarily the notebooks, potentially spin up the web app.

**Comment by milicag** [comment]
With this I would like to close this issue if that is ok?

**Comment by brynpickering** [comment]
OK, I'll close this. I'm not convinced that test results should be cluttering the core package, since everyone then has to download those images, including the majority who will never run any tests. Saying that, the package becomes quite large when accessing the databases, so it probably won't be noticed!
