### ISSUE TITLE
Add custom config file to Django web app and update footer text

### ISSUE THREAD

**Issue by hannesb0** [LBNL-ETA/MSWH#22]
Currently, the different html pages contain information like the footer text in a hard-coded way.

Action items:

- [x] Create a custom config file for static data that is used across html pages
- [x] Update footer text to `Created at and open sourced by Lawrence Berkeley National Laboratory` with link to license file

assigned to @hannesb0

**Comment by milicag** [comment]
Hannes, after some info I think the footer text should instead be: Source code available at link_to_repo. Can you please do that instead?

**Comment by hannesb0** [comment]
@milicag this PR contains the changes for the updated footer text as you wished.
