### ISSUE TITLE
Move Detailed Installation Steps to sphinx docs

### ISSUE THREAD

**Issue by milicag** [LBNL-ETA/MSWH#25]
@nmstreethran 

Now that the instructions look fine I plan to create have a page in the sphinx doc for installation instructions with mutual references as we previously agreed.

**Comment by nmstreethran** [comment]
Thanks @milicag. In ` docs/source/installation.rst`, you should fence inline code with two backticks (\`\`), not one. Otherwise, they will be formatted as italics. You may merge #28 and close this issue and #26 once you have made this change. I will then update my review checklist.

**Comment by milicag** [comment]
@nmstreethran Sounds good!
