### ISSUE TITLE
Missing contribution guidelines

### ISSUE THREAD

**Issue by brynpickering** [LBNL-ETA/MSWH#32]
The README does welcome contributions, but provides no framework doing so. [Contribution guidelines](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/setting-guidelines-for-repository-contributors) would be a clear way to set expectations in terms of structure and content of contributions, and help to ensure the [community can grow](https://opensource.guide/building-community/). They don't need to be as in-depth as projects like Atom, but sufficient to avoid confusion between your expectations and potential contributions.

Note: this issue comes to you as part of my wider [JOSS review](https://github.com/openjournals/joss-reviews/issues/2695)

**Comment by milicag** [comment]
@brynpickering Let me see what I can do. What I had in mind with the section of the readme is very simple - if you'd like to contribute, you raise an issue where you describe what the issue is for, then you hear from someone on the LBL side and address the issue using a PR. Can this live on the readme, where I'd just add a few sentences, or should I pull it out into an `rst` file again? I feel like there isn't a real need for something too elaborate, as whoever raises an issue can hear back, though you might be imagining a lot more contributions than what I anticipate will happen.

**Comment by brynpickering** [comment]
I suppose I hope for many more contributions than you anticipate! A short contribution guideline is also fine, but the flow you give in your comment here is not really given in the README. What I see here is that you expect interested parties to *first* submit an issue, then the process of addressing it with a PR can be discussed in the issue. You could describe this and also give a brief description of the kind of issues you welcome (bug reports, feature requests, etc.), for those who don't really know what's going on.

You could also think about adding [issue and PR templates](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/configuring-issue-templates-for-your-repository), if you want to ensure all issues and PRs follow some consistent structure.

**Comment by milicag** [comment]
Thank you for the thought. I will add a description to the readme similar to what I wrote in my response. I will consider a template should there start being significant contributions in the future.

**Comment by milicag** [comment]
@brynpickering What would be your preference, also from the JOSS perspective, on adding the contribution guidelines?

**Comment by sjpfenninger** [comment]
@milicag I think these can be relatively minimal, following examples given in the [GitHub documentation](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/setting-guidelines-for-repository-contributors)

**Comment by milicag** [comment]
Thanks @sjpfenninger. I also highly appreciate you writing here.
